"""
MetaGPT multi-agent baseline for affective detection (MUStARD / URFunny).

This baseline is built on the *real* MetaGPT framework: it imports
`metagpt.actions.Action`, `metagpt.actions.UserRequirement`,
`metagpt.roles.Role`, `metagpt.team.Team`, and `metagpt.schema.Message`,
and uses them exactly the way MetaGPT's own example
`MetaGPT/examples/build_customized_multi_agents.py` does.

6 roles, wired through MetaGPT's `_watch` message-routing so the SOP
progresses automatically as each role publishes its output:

    UserRequirement
         │
         ├─ TextAnalyst    ── TextAnalysisAction    ┐
         ├─ AudioAnalyst   ── AudioAnalysisAction   ├─► Synthesizer
         └─ VideoAnalyst   ── VideoAnalysisAction   ┘    │
                                                         ▼
                                                      Critic
                                                         │
                                                         ▼
                                                       Judge

Rounds: 4 (modalities → synthesis → critic → judge). Each round runs all
non-idle roles concurrently via MetaGPT's Environment.run().

Because MetaGPT's `_aask` uses its own LLM layer, we bypass it inside our
custom Actions and call `litellm.completion` directly — this keeps the LLM
call surface identical to run_moa.py / run_autogen.py for fair comparison,
so the only thing that differs between baselines is the *orchestration*.

REQUIRES: `pip install metagpt` in a dedicated env (numpy pinned to 1.26).

Examples:
    python run_metagpt.py --dataset_name mustard --max_workers 4
    python run_metagpt.py --dataset_name urfunny --resume
"""

import argparse
import asyncio
import json
import os
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from threading import Lock
from typing import Any, Dict, List, Optional

# --- Make sure MetaGPT can initialise without requiring an API key ----------
# MetaGPT's config2 loads ~/.metagpt/config2.yaml at import time. We write a
# minimal dummy config that points to our LiteLLMProvider (registered under
# `api_type: openai` below), so metagpt boots cleanly in environments with
# no stock OpenAI credentials. The actual LLM call goes through litellm.
_METAGPT_CONFIG_DIR = os.path.expanduser('~/.metagpt')
_METAGPT_CONFIG_PATH = os.path.join(_METAGPT_CONFIG_DIR, 'config2.yaml')
if not os.path.exists(_METAGPT_CONFIG_PATH):
    os.makedirs(_METAGPT_CONFIG_DIR, exist_ok=True)
    with open(_METAGPT_CONFIG_PATH, 'w') as f:
        f.write(
            '# Auto-generated by ctm-ai/exp_affective/run_metagpt.py.\n'
            '# api_type "openai" routes through LiteLLMProvider (registered\n'
            '# at import time via metagpt_litellm_provider.py), which sends\n'
            '# all requests to litellm.completion. The `model` string here\n'
            '# is the litellm model identifier, e.g. "gemini/gemini-2.5-flash-lite".\n'
            '# Delete this file to use your own MetaGPT config instead.\n'
            'llm:\n'
            '  api_type: "openai"\n'
            '  model: "gemini/gemini-2.5-flash-lite"\n'
            '  api_key: "sk-unused-litellm-uses-GEMINI_API_KEY-env-var"\n'
            '  calc_usage: false\n'
        )

from metagpt.actions import Action, UserRequirement  # noqa: E402
from metagpt.roles import Role  # noqa: E402
from metagpt.schema import Message  # noqa: E402
from metagpt.team import Team  # noqa: E402
from pydantic import Field  # noqa: E402

# Import (and thereby register) our LiteLLMProvider under LLMType.OPENAI.
# This must come AFTER metagpt's own provider registration (triggered by
# the imports above) so that our provider overrides the stock one.
import metagpt_litellm_provider  # noqa: E402, F401

# --- Project imports --------------------------------------------------------
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from dataset_configs import get_dataset_config  # noqa: E402
from llm_utils import (  # noqa: E402
    get_audio_path,
    get_muted_video_path,
    load_data,
)

file_lock = Lock()

DEFAULT_MODEL = 'gemini/gemini-2.5-flash-lite'


# =============================================================================
# Prompts (loaded from CTM config for fair comparison with other baselines)
# =============================================================================

def _load_ctm_prompts(dataset_name='mustard'):
    config_map = {
        'mustard': 'sarcasm_ctm_config.json',
        # urfunny: use the Gemini-tuned config (was wrongly using
        # urfunny_test_qwen_v12_config.json which is calibrated for Qwen).
        'urfunny': 'urfunny_test_gemini_v28_config.json',
    }
    config_path = os.path.join(
        os.path.dirname(__file__), '..', 'ctm_conf',
        config_map.get(dataset_name, config_map['mustard']),
    )
    with open(config_path) as f:
        cfg = json.load(f)
    return cfg['processors_config']


def _build_pipeline_prompts(dataset_name='mustard'):
    """Return synthesiser/critic/judge system prompts for the target task."""
    if dataset_name == 'urfunny':
        task = 'humor detection'
        yes_label = 'humorous'
        no_label = 'not humorous'
        pitfalls = (
            '   - Enthusiasm/excitement vs actual humorous intent\n'
            '   - Deadpan delivery with comedic intent\n'
            '   - Informative surprises vs real jokes\n'
            '   - Rhetorical contrasts vs humorous incongruity'
        )
    else:
        task = 'sarcasm detection'
        yes_label = 'sarcastic'
        no_label = 'not sarcastic'
        pitfalls = (
            '   - Genuine anger/frustration vs sarcasm\n'
            '   - Dry/deadpan delivery vs sarcastic intent\n'
            '   - Playful teasing vs sarcasm\n'
            '   - Short responses as automatically non-sarcastic'
        )

    synthesizer = (
        f'You are the Synthesizer in a multi-agent {task} team. '
        'You have received independent analysis reports from three modality '
        'experts (Text, Audio, Video). Integrate them into a coherent '
        'cross-modal synthesis covering:\n'
        '1. **Agreement Points**: Where do the experts agree?\n'
        '2. **Conflicts**: Where do they disagree? Which has stronger evidence?\n'
        f'3. **Evidence Strength**: Rate the overall evidence for {yes_label} '
        f'vs {no_label}.\n'
        '4. **Modality Reliability**: For this sample, which modality is '
        'most reliable and why?\n'
        f'5. **Synthesis Verdict**: Is the person likely {yes_label} or not?'
    )
    critic = (
        f'You are the Critic in a multi-agent {task} team. '
        'You have received the modality analyses and the synthesizer\'s '
        'integration. Critically review the synthesis covering:\n'
        '1. **Logical Consistency**: Are conclusions supported by evidence?\n'
        '2. **Overlooked Evidence**: Was anything under-weighted?\n'
        '3. **Common Pitfalls**: Flag if the analysis might confuse:\n'
        f'{pitfalls}\n'
        '4. **Uncertainty Assessment**: How confident is the judgment?\n'
        '5. **Revised Verdict**: Do you agree with the synthesis? Why?'
    )
    judge = (
        f'You are the Final Judge in a multi-agent {task} team. You have '
        'received modality reports, a cross-modal synthesis, and a critic '
        'review. Make the final determination.\n\n'
        f'Your answer MUST start with exactly "Yes" ({yes_label}) or "No" '
        f'({no_label}), then a brief justification citing the most decisive '
        'evidence.\n\n'
        'Guidelines:\n'
        f'- If the Critic identified significant weaknesses in the '
        f'{yes_label} case, weigh that heavily.\n'
        '- If modalities strongly agree, trust the consensus.\n'
        '- If modalities conflict, prioritize text > audio > video for '
        'semantic judgment.\n'
        '- Make a definitive decision — do not hedge.'
    )
    return synthesizer, critic, judge


# =============================================================================
# MetaGPT Actions (the 6 stages of the SOP)
# =============================================================================
#
# Each Action is a metagpt.actions.Action subclass that calls the LLM via
# the canonical metagpt interface:
#   - text-only stages  → `await self._aask(prompt, system_msgs=[...])`
#     which internally hits `self.llm.aask(...)` → LiteLLMProvider
#   - audio / video stages → `await self.llm.aask_multimodal(prompt, ...)`,
#     a local extension on our LiteLLMProvider that builds multimodal
#     content payloads and routes through the same litellm pipeline.
#
# Actions cache their last usage (from self.llm.last_response_usage, which
# the provider updates on every call) so the driver can aggregate per-sample
# token counts afterwards without having to poll metagpt's cost_manager.
# =============================================================================


def _capture_usage(action: 'Action') -> None:
    """Copy the LLM provider's last_response_usage onto the Action so
    _collect_usage_from_roles can read it later. No-op if the provider
    hasn't populated it (e.g. an empty-file short-circuit)."""
    usage = getattr(action.llm, 'last_response_usage', None) or {}
    if usage:
        action.last_usage = dict(usage)


class _ModalityAction(Action):
    """Base class for text/audio/video analysis actions."""
    system_prompt: str = ''
    last_usage: Dict[str, Any] = Field(default_factory=dict)


class TextAnalysisAction(_ModalityAction):
    name: str = 'TextAnalysisAction'

    async def run(self, query: str, target_sentence: str) -> str:
        prompt = f'{query}\n\nDialogue transcript:\n{target_sentence}'
        text = await self._aask(prompt, system_msgs=[self.system_prompt])
        _capture_usage(self)
        return text or '[text analysis failed]'


class AudioAnalysisAction(_ModalityAction):
    name: str = 'AudioAnalysisAction'

    async def run(self, query: str, audio_path: Optional[str]) -> str:
        if not audio_path or not os.path.exists(audio_path):
            self.last_usage = {'prompt_tokens': 0, 'completion_tokens': 0,
                               'total_tokens': 0, 'api_calls': 0, 'latency': 0.0}
            return '[Audio unavailable]'
        prompt = f'{query}\n\nAnalyze the audio and produce your report.'
        text = await self.llm.aask_multimodal(
            prompt, system_msgs=[self.system_prompt], audio_path=audio_path,
        )
        _capture_usage(self)
        return text or '[audio analysis failed]'


class VideoAnalysisAction(_ModalityAction):
    name: str = 'VideoAnalysisAction'

    async def run(self, query: str, video_path: Optional[str]) -> str:
        if not video_path or not os.path.exists(video_path):
            self.last_usage = {'prompt_tokens': 0, 'completion_tokens': 0,
                               'total_tokens': 0, 'api_calls': 0, 'latency': 0.0}
            return '[Video unavailable]'
        prompt = f'{query}\n\nAnalyze the muted video and produce your report.'
        text = await self.llm.aask_multimodal(
            prompt, system_msgs=[self.system_prompt], video_path=video_path,
        )
        _capture_usage(self)
        return text or '[video analysis failed]'


class SynthesisAction(Action):
    name: str = 'SynthesisAction'
    system_prompt: str = ''
    last_usage: Dict[str, Any] = Field(default_factory=dict)

    async def run(self, query: str, text_report: str, audio_report: str,
                  video_report: str) -> str:
        prompt = (
            f'Task: {query}\n\n'
            f'=== TEXT ANALYST REPORT ===\n{text_report}\n\n'
            f'=== AUDIO ANALYST REPORT ===\n{audio_report}\n\n'
            f'=== VIDEO ANALYST REPORT ===\n{video_report}\n\n'
            'Produce your cross-modal synthesis.'
        )
        text = await self._aask(prompt, system_msgs=[self.system_prompt])
        _capture_usage(self)
        return text or '[synthesis failed]'


class CriticAction(Action):
    name: str = 'CriticAction'
    system_prompt: str = ''
    last_usage: Dict[str, Any] = Field(default_factory=dict)

    async def run(self, query: str, text_report: str, audio_report: str,
                  video_report: str, synthesis: str) -> str:
        prompt = (
            f'Task: {query}\n\n'
            f'=== TEXT ANALYST REPORT ===\n{text_report}\n\n'
            f'=== AUDIO ANALYST REPORT ===\n{audio_report}\n\n'
            f'=== VIDEO ANALYST REPORT ===\n{video_report}\n\n'
            f'=== SYNTHESIZER REPORT ===\n{synthesis}\n\n'
            'Critically review the synthesis. Identify weaknesses, '
            'overlooked evidence, and potential errors.'
        )
        text = await self._aask(prompt, system_msgs=[self.system_prompt])
        _capture_usage(self)
        return text or '[critique failed]'


class JudgeAction(Action):
    name: str = 'JudgeAction'
    system_prompt: str = ''
    last_usage: Dict[str, Any] = Field(default_factory=dict)

    async def run(self, query: str, text_report: str, audio_report: str,
                  video_report: str, synthesis: str, critique: str) -> str:
        prompt = (
            f'Task: {query}\n\n'
            f'=== TEXT ANALYST REPORT ===\n{text_report}\n\n'
            f'=== AUDIO ANALYST REPORT ===\n{audio_report}\n\n'
            f'=== VIDEO ANALYST REPORT ===\n{video_report}\n\n'
            f'=== SYNTHESIZER REPORT ===\n{synthesis}\n\n'
            f'=== CRITIC REVIEW ===\n{critique}\n\n'
            'Make your final determination. Start with "Yes" or "No".'
        )
        text = await self._aask(prompt, system_msgs=[self.system_prompt])
        _capture_usage(self)
        return text or '[judgment failed]'


# =============================================================================
# MetaGPT Roles
# =============================================================================
#
# Each Role subclasses metagpt.roles.Role. It:
#   1. Uses `_watch(...)` to subscribe to upstream Actions
#   2. Uses `set_actions(...)` to install its own Action(s)
#   3. Overrides `_act()` to thread sample-specific data into its Action
#
# Sample data (target_sentence, audio_path, video_path, query) is stored as
# Pydantic fields on the Role instance. We create a fresh set of roles per
# sample (roles are stateful in MetaGPT).
# =============================================================================

class _BaseAnalyst(Role):
    """Base for modality analyst roles watching UserRequirement."""
    query: str = ''
    target_sentence: str = ''
    audio_path: Optional[str] = None
    video_path: Optional[str] = None
    # Captures the Action's output so the driver can read it directly without
    # replaying MetaGPT's broadcast-and-observe cycle through another round.
    last_output: str = ''


class TextAnalyst(_BaseAnalyst):
    name: str = 'TextAnalyst'
    profile: str = 'Text Modality Analyst'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        system_prompt = kwargs.get('system_prompt', '')
        action = TextAnalysisAction(
            system_prompt=system_prompt,
        )
        self.set_actions([action])
        self._watch([UserRequirement])

    async def _act(self) -> Message:
        todo: TextAnalysisAction = self.rc.todo  # type: ignore[assignment]
        result = await todo.run(
            query=self.query, target_sentence=self.target_sentence,
        )
        self.last_output = result
        msg = Message(
            content=result, role=self.profile, cause_by=TextAnalysisAction,
            sent_from=self.name,
        )
        self.rc.memory.add(msg)
        return msg


class AudioAnalyst(_BaseAnalyst):
    name: str = 'AudioAnalyst'
    profile: str = 'Audio Modality Analyst'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        system_prompt = kwargs.get('system_prompt', '')
        action = AudioAnalysisAction(
            system_prompt=system_prompt,
        )
        self.set_actions([action])
        self._watch([UserRequirement])

    async def _act(self) -> Message:
        todo: AudioAnalysisAction = self.rc.todo  # type: ignore[assignment]
        result = await todo.run(query=self.query, audio_path=self.audio_path)
        self.last_output = result
        msg = Message(
            content=result, role=self.profile, cause_by=AudioAnalysisAction,
            sent_from=self.name,
        )
        self.rc.memory.add(msg)
        return msg


class VideoAnalyst(_BaseAnalyst):
    name: str = 'VideoAnalyst'
    profile: str = 'Video Modality Analyst'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        system_prompt = kwargs.get('system_prompt', '')
        action = VideoAnalysisAction(
            system_prompt=system_prompt,
        )
        self.set_actions([action])
        self._watch([UserRequirement])

    async def _act(self) -> Message:
        todo: VideoAnalysisAction = self.rc.todo  # type: ignore[assignment]
        result = await todo.run(query=self.query, video_path=self.video_path)
        self.last_output = result
        msg = Message(
            content=result, role=self.profile, cause_by=VideoAnalysisAction,
            sent_from=self.name,
        )
        self.rc.memory.add(msg)
        return msg


class Synthesizer(Role):
    name: str = 'Synthesizer'
    profile: str = 'Cross-Modal Synthesizer'
    query: str = ''
    last_output: str = ''

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        system_prompt = kwargs.get('system_prompt', '')
        action = SynthesisAction(
            system_prompt=system_prompt,
        )
        self.set_actions([action])
        # Synthesizer becomes non-idle once any modality analysis arrives,
        # but we gate actual execution on having *all three* via _think().
        self._watch([TextAnalysisAction, AudioAnalysisAction, VideoAnalysisAction])

    async def _think(self) -> bool:
        # Wait until memory contains at least one message from each of the
        # three modality experts. MetaGPT's env.run() runs all roles in a
        # single asyncio.gather per round, which means downstream roles can
        # observe partial upstream output during the same round and react
        # early — producing duplicate downstream actions. Gating on memory
        # contents here ensures Synthesizer fires exactly once when the
        # full set of modality reports is available.
        cbs = [str(m.cause_by) for m in self.rc.memory.get()]
        has_text = any('TextAnalysisAction' in c for c in cbs)
        has_audio = any('AudioAnalysisAction' in c for c in cbs)
        has_video = any('VideoAnalysisAction' in c for c in cbs)
        if not (has_text and has_audio and has_video):
            self._set_state(-1)
            return False
        self._set_state(0)
        return True

    def _collect_reports(self) -> Dict[str, str]:
        """Pull the latest text/audio/video reports from our own memory.
        Message.cause_by is normalised to a class-path string by MetaGPT's
        `any_to_str` validator, so we match by substring."""
        reports = {'text': '[text missing]', 'audio': '[audio missing]',
                   'video': '[video missing]'}
        for msg in self.rc.memory.get():
            cb_str = str(msg.cause_by)
            if 'TextAnalysisAction' in cb_str:
                reports['text'] = msg.content
            elif 'AudioAnalysisAction' in cb_str:
                reports['audio'] = msg.content
            elif 'VideoAnalysisAction' in cb_str:
                reports['video'] = msg.content
        return reports

    async def _act(self) -> Message:
        todo: SynthesisAction = self.rc.todo  # type: ignore[assignment]
        reports = self._collect_reports()
        result = await todo.run(
            query=self.query,
            text_report=reports['text'],
            audio_report=reports['audio'],
            video_report=reports['video'],
        )
        self.last_output = result
        msg = Message(
            content=result, role=self.profile, cause_by=SynthesisAction,
            sent_from=self.name,
        )
        self.rc.memory.add(msg)
        return msg


class Critic(Role):
    name: str = 'Critic'
    profile: str = 'Critical Reviewer'
    query: str = ''
    last_output: str = ''
    # In metagpt 0.8.2 Role._observe() already adds every popped message to
    # memory (only rc.news is filtered), so Critic's memory naturally retains
    # the upstream modality reports published in round 1 even though it
    # only *reacts* to SynthesisAction in round 3.

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        system_prompt = kwargs.get('system_prompt', '')
        action = CriticAction(system_prompt=system_prompt)
        self.set_actions([action])
        self._watch([SynthesisAction])

    async def _think(self) -> bool:
        cbs = [str(m.cause_by) for m in self.rc.memory.get()]
        needed = ['TextAnalysisAction', 'AudioAnalysisAction',
                  'VideoAnalysisAction', 'SynthesisAction']
        if not all(any(n in c for c in cbs) for n in needed):
            self._set_state(-1)
            return False
        self._set_state(0)
        return True

    def _collect_reports(self) -> Dict[str, str]:
        reports = {'text': '[text missing]', 'audio': '[audio missing]',
                   'video': '[video missing]', 'synthesis': '[synthesis missing]'}
        for msg in self.rc.memory.get():
            cb_str = str(msg.cause_by)
            if 'TextAnalysisAction' in cb_str:
                reports['text'] = msg.content
            elif 'AudioAnalysisAction' in cb_str:
                reports['audio'] = msg.content
            elif 'VideoAnalysisAction' in cb_str:
                reports['video'] = msg.content
            elif 'SynthesisAction' in cb_str:
                reports['synthesis'] = msg.content
        return reports

    async def _act(self) -> Message:
        todo: CriticAction = self.rc.todo  # type: ignore[assignment]
        reports = self._collect_reports()
        result = await todo.run(
            query=self.query,
            text_report=reports['text'],
            audio_report=reports['audio'],
            video_report=reports['video'],
            synthesis=reports['synthesis'],
        )
        self.last_output = result
        msg = Message(
            content=result, role=self.profile, cause_by=CriticAction,
            sent_from=self.name,
        )
        self.rc.memory.add(msg)
        return msg


class Judge(Role):
    name: str = 'Judge'
    profile: str = 'Final Judge'
    query: str = ''
    last_output: str = ''
    # Same as Critic: metagpt 0.8.2 keeps all observed messages in memory,
    # so Judge naturally sees modality reports + synthesis + critique by the
    # time it runs in round 4.

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        system_prompt = kwargs.get('system_prompt', '')
        action = JudgeAction(system_prompt=system_prompt)
        self.set_actions([action])
        self._watch([CriticAction])

    async def _think(self) -> bool:
        cbs = [str(m.cause_by) for m in self.rc.memory.get()]
        needed = ['TextAnalysisAction', 'AudioAnalysisAction',
                  'VideoAnalysisAction', 'SynthesisAction', 'CriticAction']
        if not all(any(n in c for c in cbs) for n in needed):
            self._set_state(-1)
            return False
        self._set_state(0)
        return True

    def _collect_reports(self) -> Dict[str, str]:
        reports = {'text': '[text missing]', 'audio': '[audio missing]',
                   'video': '[video missing]', 'synthesis': '[synthesis missing]',
                   'critique': '[critique missing]'}
        for msg in self.rc.memory.get():
            cb_str = str(msg.cause_by)
            if 'TextAnalysisAction' in cb_str:
                reports['text'] = msg.content
            elif 'AudioAnalysisAction' in cb_str:
                reports['audio'] = msg.content
            elif 'VideoAnalysisAction' in cb_str:
                reports['video'] = msg.content
            elif 'SynthesisAction' in cb_str:
                reports['synthesis'] = msg.content
            elif 'CriticAction' in cb_str:
                reports['critique'] = msg.content
        return reports

    async def _act(self) -> Message:
        todo: JudgeAction = self.rc.todo  # type: ignore[assignment]
        reports = self._collect_reports()
        result = await todo.run(
            query=self.query,
            text_report=reports['text'],
            audio_report=reports['audio'],
            video_report=reports['video'],
            synthesis=reports['synthesis'],
            critique=reports['critique'],
        )
        self.last_output = result
        msg = Message(
            content=result, role=self.profile, cause_by=JudgeAction,
            sent_from=self.name,
        )
        self.rc.memory.add(msg)
        return msg


# =============================================================================
# Per-sample driver: build a fresh Team and run it
# =============================================================================

def _collect_usage_from_roles(roles) -> Dict[str, Any]:
    """Walk each role's Actions and sum up their `last_usage` dicts."""
    totals = {
        'total_api_calls': 0,
        'total_prompt_tokens': 0,
        'total_completion_tokens': 0,
        'total_tokens': 0,
        'stage_latencies': {},
    }
    for role in roles:
        for action in role.actions:
            u = getattr(action, 'last_usage', {}) or {}
            totals['total_api_calls'] += u.get('api_calls', 0)
            totals['total_prompt_tokens'] += u.get('prompt_tokens', 0)
            totals['total_completion_tokens'] += u.get('completion_tokens', 0)
            totals['total_tokens'] += u.get('total_tokens', 0)
            totals['stage_latencies'][action.name] = u.get('latency', 0.0)
    return totals


def _extract_final_answer_and_reports(roles) -> Dict[str, str]:
    """Each Role caches its Action output in `last_output` during `_act()`,
    so after team.run() finishes we can read them directly without relying
    on an extra 'drain' round of MetaGPT's broadcast-and-observe cycle."""
    out = {'text': '', 'audio': '', 'video': '',
           'synthesis': '', 'critique': '', 'judgment': ''}
    for r in roles:
        if isinstance(r, TextAnalyst):
            out['text'] = r.last_output
        elif isinstance(r, AudioAnalyst):
            out['audio'] = r.last_output
        elif isinstance(r, VideoAnalyst):
            out['video'] = r.last_output
        elif isinstance(r, Synthesizer):
            out['synthesis'] = r.last_output
        elif isinstance(r, Critic):
            out['critique'] = r.last_output
        elif isinstance(r, Judge):
            out['judgment'] = r.last_output
    return out


async def run_metagpt_sample_async(
    query: str, target_sentence: str,
    audio_path: Optional[str], video_path: Optional[str],
    text_system: str, audio_system: str, video_system: str,
    synthesizer_system: str, critic_system: str, judge_system: str,
    n_round: int = 4,
):
    """Build a fresh Team and run the SOP for one sample.

    The LLM model is NOT passed here — every Role's `self.llm` is built
    by metagpt from `~/.metagpt/config2.yaml`, where `llm.model` holds the
    litellm model identifier (e.g. "gemini/gemini-2.5-flash-lite").
    """
    text_role = TextAnalyst(
        query=query, target_sentence=target_sentence,
        system_prompt=text_system,
    )
    audio_role = AudioAnalyst(
        query=query, audio_path=audio_path,
        system_prompt=audio_system,
    )
    video_role = VideoAnalyst(
        query=query, video_path=video_path,
        system_prompt=video_system,
    )
    synth_role = Synthesizer(
        query=query, system_prompt=synthesizer_system,
    )
    critic_role = Critic(
        query=query, system_prompt=critic_system,
    )
    judge_role = Judge(
        query=query, system_prompt=judge_system,
    )
    roles = [text_role, audio_role, video_role,
             synth_role, critic_role, judge_role]

    team = Team()
    team.hire(roles)
    team.invest(investment=10.0)  # high enough to avoid cost-abort
    team.run_project(query)
    await team.run(n_round=n_round)

    reports = _extract_final_answer_and_reports(roles)
    usage = _collect_usage_from_roles(roles)
    return reports, usage


def _parse_yes_no(text: str) -> str:
    """Extract 'Yes'/'No' from the judge's reply."""
    if not text:
        return ''
    head = text.strip()[:16].lower()
    if head.startswith('yes'):
        return 'Yes'
    if head.startswith('no'):
        return 'No'
    lower = text.lower()
    if 'yes' in lower and 'no' not in lower[:lower.find('yes')+3]:
        return 'Yes'
    if 'no' in lower:
        return 'No'
    return ''


# =============================================================================
# Instance runner (sync wrapper; one fresh event loop per thread)
# =============================================================================

def run_instance(test_file, dataset, dataset_name, output_file,
                 ctm_prompts, pipeline_prompts):
    try:
        config = get_dataset_config(dataset_name)
        sample = dataset[test_file]
        target_sentence = config.get_text_field(sample)
        label = config.get_label_field(sample)
        query = config.get_task_query()

        audio_path = get_audio_path(test_file, dataset_name)
        video_path = get_muted_video_path(test_file, dataset_name)
        if not os.path.exists(audio_path):
            audio_path = None
        if not os.path.exists(video_path):
            video_path = None

        synth_prompt, critic_prompt, judge_prompt = pipeline_prompts
        start_time = time.time()
        reports, usage_stats = asyncio.run(run_metagpt_sample_async(
            query=query, target_sentence=target_sentence,
            audio_path=audio_path, video_path=video_path,
            text_system=ctm_prompts['language_processor']['system_prompt'],
            audio_system=ctm_prompts['audio_processor']['system_prompt'],
            video_system=ctm_prompts['video_processor']['system_prompt'],
            synthesizer_system=synth_prompt,
            critic_system=critic_prompt,
            judge_system=judge_prompt,
        ))
        elapsed = time.time() - start_time

        final_answer = reports.get('judgment', '') or ''
        parsed = _parse_yes_no(final_answer)
        print(
            f'[{test_file}] {elapsed:.1f}s | api={usage_stats["total_api_calls"]} '
            f'tok={usage_stats["total_tokens"]} | {final_answer[:60]}'
        )

        result = {
            test_file: {
                'answer': [final_answer],
                'parsed_answer': [parsed],
                'label': label,
                'method': 'metagpt_framework',
                'latency': elapsed,
                'api_calls': usage_stats['total_api_calls'],
                'prompt_tokens': usage_stats['total_prompt_tokens'],
                'completion_tokens': usage_stats['total_completion_tokens'],
                'total_tokens': usage_stats['total_tokens'],
                'stage_latencies': usage_stats['stage_latencies'],
                'stage_outputs': {
                    'text_report': reports.get('text', ''),
                    'audio_report': reports.get('audio', ''),
                    'video_report': reports.get('video', ''),
                    'synthesis': reports.get('synthesis', ''),
                    'critique': reports.get('critique', ''),
                },
            }
        }

        with file_lock:
            with open(output_file, 'a', encoding='utf-8') as f:
                f.write(json.dumps(result, ensure_ascii=False) + '\n')
        return f'OK {test_file}'

    except Exception as e:
        print(f'[{test_file}] ERROR: {e}')
        import traceback
        traceback.print_exc()
        return f'FAIL {test_file}: {e}'


# =============================================================================
# Parallel runner
# =============================================================================

def load_processed_keys(output_file):
    processed = set()
    try:
        with open(output_file, 'r', encoding='utf-8') as f:
            for line in f:
                if line.strip():
                    processed.update(json.loads(line).keys())
    except FileNotFoundError:
        pass
    return processed


def run_parallel(dataset, dataset_name, max_workers, output_file, resume,
                 sleep_between, ctm_prompts, pipeline_prompts):
    test_list = list(dataset.keys())

    if resume:
        processed = load_processed_keys(output_file)
        test_list = [k for k in test_list if k not in processed]
        print(f'Resume: {len(processed)} done, {len(test_list)} remaining')
    else:
        with open(output_file, 'w', encoding='utf-8'):
            pass

    if not test_list:
        print('Nothing to do.')
        return

    print('=' * 60)
    print('MetaGPT framework SOP (6 roles) via LiteLLMProvider')
    print(f'Samples: {len(test_list)} | Workers: {max_workers}')
    print(f'Output: {output_file}')
    print('=' * 60)

    start_time = time.time()
    completed = 0

    if max_workers == 1 and sleep_between > 0:
        for t in test_list:
            run_instance(t, dataset, dataset_name, output_file,
                         ctm_prompts, pipeline_prompts)
            completed += 1
            print(f'Progress: {completed}/{len(test_list)}')
            if completed < len(test_list):
                time.sleep(sleep_between)
    else:
        with ThreadPoolExecutor(max_workers=max_workers) as executor:
            futures = {
                executor.submit(
                    run_instance, t, dataset, dataset_name, output_file,
                    ctm_prompts, pipeline_prompts,
                ): t for t in test_list
            }
            for future in as_completed(futures):
                completed += 1
                try:
                    result = future.result()
                    print(f'Progress: {completed}/{len(test_list)} - {result}')
                except Exception as exc:
                    print(f'Error: {exc}')

    wall_time = time.time() - start_time
    _print_summary(output_file, wall_time)


def _print_summary(output_file, wall_time):
    total_api = total_pt = total_ct = total_tok = 0
    latencies: List[float] = []
    n = 0
    try:
        with open(output_file) as f:
            for line in f:
                if not line.strip():
                    continue
                for _, val in json.loads(line).items():
                    n += 1
                    total_api += val.get('api_calls', 0)
                    total_pt += val.get('prompt_tokens', 0)
                    total_ct += val.get('completion_tokens', 0)
                    total_tok += val.get('total_tokens', 0)
                    latencies.append(val.get('latency', 0.0))
    except Exception as e:
        print(f'Warning: {e}')
        return

    if n == 0:
        return

    cost = total_pt / 1e6 * 0.075 + total_ct / 1e6 * 0.30
    print(f'\n{"=" * 60}')
    print('METAGPT (framework) PERFORMANCE & COST SUMMARY')
    print('=' * 60)
    print(f'Samples:                  {n}')
    print(f'Wall-clock:               {wall_time:.1f}s')
    print('-' * 40)
    print(f'Total API Calls:          {total_api}')
    print(f'Avg API Calls/Sample:     {total_api / n:.1f}')
    print(f'Avg Latency/Sample:       {sum(latencies) / n:.2f}s')
    print('-' * 40)
    print(f'Total Prompt Tokens:      {total_pt:,}')
    print(f'Total Completion Tokens:  {total_ct:,}')
    print(f'Total Tokens:             {total_tok:,}')
    print(f'Avg Tokens/Sample:        {total_tok / n:,.0f}')
    print('-' * 40)
    print(f'Estimated Cost:           ${cost:.4f}')
    print(f'Avg Cost/Sample:          ${cost / n:.6f}')
    print('=' * 60 + '\n')


# =============================================================================
# CLI
# =============================================================================

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='MetaGPT framework baseline for affective detection. '
                    'Uses metagpt.Role/Action/Team directly — run in the '
                    'dedicated ctm-baselines conda env.',
    )
    parser.add_argument('--dataset_name', type=str, default='mustard',
                        choices=['urfunny', 'mustard'])
    parser.add_argument('--dataset', type=str, default=None)
    parser.add_argument('--output', type=str, default=None)
    parser.add_argument(
        '--model', type=str, default=None,
        help='Override the litellm model identifier (e.g. '
             '"gemini/gemini-2.5-flash-lite", "gpt-4o"). If omitted, '
             'falls back to the value in ~/.metagpt/config2.yaml.',
    )
    parser.add_argument('--max_workers', type=int, default=4)
    parser.add_argument('--resume', action='store_true')
    parser.add_argument('--sleep', type=float, default=0)
    args = parser.parse_args()

    # Apply --model override directly on metagpt's global config, BEFORE
    # any Role/Action is instantiated (they lazily materialise their LLM
    # from this global config via ContextMixin).
    if args.model:
        from metagpt.config2 import config as metagpt_config
        metagpt_config.llm.model = args.model

    config = get_dataset_config(args.dataset_name)
    if args.dataset is None:
        args.dataset = config.get_default_dataset_path()

    ctm_prompts = _load_ctm_prompts(args.dataset_name)
    pipeline_prompts = _build_pipeline_prompts(args.dataset_name)

    output_file = args.output or f'metagpt_{args.dataset_name}.jsonl'

    dataset = load_data(args.dataset)
    from metagpt.config2 import config as _effective_cfg
    print(f'Dataset: {args.dataset_name} | Model: {_effective_cfg.llm.model} | '
          f'Samples: {len(dataset)}')

    run_parallel(
        dataset, args.dataset_name,
        max_workers=args.max_workers, output_file=output_file,
        resume=args.resume, sleep_between=args.sleep,
        ctm_prompts=ctm_prompts, pipeline_prompts=pipeline_prompts,
    )
