"""
MetaGPT multi-agent baseline for affective detection (MUStARD / URFunny).

This baseline is built on the *real* MetaGPT framework: it imports
`metagpt.actions.Action`, `metagpt.actions.UserRequirement`,
`metagpt.roles.Role`, `metagpt.team.Team`, and `metagpt.schema.Message`,
and uses them exactly the way MetaGPT's own example
`MetaGPT/examples/build_customized_multi_agents.py` does.

6 roles, wired through MetaGPT's `_watch` message-routing so the SOP
progresses automatically as each role publishes its output:

    UserRequirement
         │
         ├─ TextAnalyst    ── TextAnalysisAction    ┐
         ├─ AudioAnalyst   ── AudioAnalysisAction   ├─► Synthesizer
         └─ VideoAnalyst   ── VideoAnalysisAction   ┘    │
                                                         ▼
                                                      Critic
                                                         │
                                                         ▼
                                                       Judge

Rounds: 4 (modalities → synthesis → critic → judge). Each round runs all
non-idle roles concurrently via MetaGPT's Environment.run().

Because MetaGPT's `_aask` uses its own LLM layer, we bypass it inside our
custom Actions and call `litellm.completion` directly — this keeps the LLM
call surface identical to run_moa.py / run_autogen.py for fair comparison,
so the only thing that differs between baselines is the *orchestration*.

REQUIRES: `pip install metagpt` in a dedicated env (numpy pinned to 1.26).

Examples:
    python run_metagpt.py --dataset_name mustard --max_workers 4
    python run_metagpt.py --dataset_name urfunny --resume
"""

import argparse
import asyncio
import base64
import json
import os
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from threading import Lock
from typing import Any, Dict, List, Optional

import litellm

# --- Make sure MetaGPT can initialise without requiring an API key ----------
# MetaGPT's config2 loads ~/.metagpt/config2.yaml at import time. When that
# file is missing it normally asks the user to set one up. We write a minimal
# dummy config on first run so the framework boots in environments where no
# MetaGPT-specific credentials exist. We never call `_aask`, so the dummy
# values are never actually used.
_METAGPT_CONFIG_DIR = os.path.expanduser('~/.metagpt')
_METAGPT_CONFIG_PATH = os.path.join(_METAGPT_CONFIG_DIR, 'config2.yaml')
if not os.path.exists(_METAGPT_CONFIG_PATH):
    os.makedirs(_METAGPT_CONFIG_DIR, exist_ok=True)
    with open(_METAGPT_CONFIG_PATH, 'w') as f:
        f.write(
            '# Auto-generated by ctm-ai/exp_affective/run_metagpt.py.\n'
            '# This baseline bypasses metagpt._aask and calls litellm\n'
            '# directly, so these credentials are never actually used.\n'
            '# Delete this file to use your own MetaGPT config instead.\n'
            'llm:\n'
            '  api_type: "openai"\n'
            '  model: "gpt-4o-mini"\n'
            '  base_url: "https://api.openai.com/v1"\n'
            '  api_key: "sk-dummy-metagpt-baseline-bypass-aask"\n'
        )

from metagpt.actions import Action, UserRequirement  # noqa: E402
from metagpt.roles import Role  # noqa: E402
from metagpt.schema import Message  # noqa: E402
from metagpt.team import Team  # noqa: E402
from pydantic import Field  # noqa: E402

# --- Project imports --------------------------------------------------------
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from dataset_configs import get_dataset_config  # noqa: E402
from llm_utils import (  # noqa: E402
    get_audio_path,
    get_muted_video_path,
    load_data,
)

file_lock = Lock()

DEFAULT_MODEL = 'gemini/gemini-2.5-flash-lite'


# =============================================================================
# Shared LLM call (bypasses metagpt's _aask so the LLM surface matches other
# baselines). Supports text-only and multimodal message lists.
# =============================================================================

def _call_llm(messages, model, max_retries=3):
    """Call litellm.completion with retry. Returns (text, usage)."""
    start = time.time()
    api_calls = 0
    for attempt in range(1, max_retries + 1):
        try:
            api_calls += 1
            resp = litellm.completion(
                model=model, messages=messages, temperature=0.0,
            )
            text = resp.choices[0].message.content
            usage = {
                'prompt_tokens': getattr(resp.usage, 'prompt_tokens', 0) or 0,
                'completion_tokens': getattr(resp.usage, 'completion_tokens', 0) or 0,
                'total_tokens': getattr(resp.usage, 'total_tokens', 0) or 0,
                'api_calls': api_calls,
                'latency': time.time() - start,
            }
            if text:
                return text.strip(), usage
        except Exception as e:
            print(f'  LLM attempt {attempt}/{max_retries} failed: {e}')
            if attempt < max_retries:
                time.sleep(2 ** attempt)
    return None, {
        'prompt_tokens': 0, 'completion_tokens': 0, 'total_tokens': 0,
        'api_calls': api_calls, 'latency': time.time() - start,
    }


def _encode_file(path):
    with open(path, 'rb') as f:
        return base64.b64encode(f.read()).decode('utf-8')


def _audio_mime(path):
    ext = path.split('.')[-1].lower()
    return {
        'mp3': 'audio/mp3', 'wav': 'audio/wav',
        'mp4': 'audio/mp4', 'aac': 'audio/aac',
    }.get(ext, 'audio/mp4')


# =============================================================================
# Prompts (loaded from CTM config for fair comparison with other baselines)
# =============================================================================

def _load_ctm_prompts(dataset_name='mustard'):
    config_map = {
        'mustard': 'sarcasm_ctm_config.json',
        'urfunny': 'urfunny_test_qwen_v12_config.json',
    }
    config_path = os.path.join(
        os.path.dirname(__file__), '..', 'ctm_conf',
        config_map.get(dataset_name, config_map['mustard']),
    )
    with open(config_path) as f:
        cfg = json.load(f)
    return cfg['processors_config']


def _build_pipeline_prompts(dataset_name='mustard'):
    """Return synthesiser/critic/judge system prompts for the target task.

    Key design choices (motivated by the empirical observation that the
    previous hand-written prompts under-performed on MUStARD):
    - Explicit incongruity framing — sarcasm/humor is fundamentally about
      mismatch, and this is the single strongest signal.
    - The Critic audits in BOTH directions (false positive AND false
      negative), instead of only flagging "might be mistaking X for
      sarcasm". The previous asymmetric critic biased the pipeline toward
      "not sarcastic".
    - Neutral prior: MUStARD is balanced ≈50/50, so "default to No under
      uncertainty" is systematically wrong. Remove that bias.
    - Judge output format is strict: "Yes/No + one sentence", to keep the
      parser (calc_ctm_res.extract_prediction) happy.
    """
    if dataset_name == 'urfunny':
        task = 'humor detection'
        yes_label = 'humorous'
        no_label = 'not humorous'
        core_def = (
            'Humor is characterised by UNEXPECTED INCONGRUITY — a gap between '
            'setup and punchline, absurd comparisons, self-deprecation, ironic '
            'observations, or twists that subvert expectation.'
        )
        signals = (
            '- Setup/punchline structure: buildup followed by an unexpected payoff.\n'
            '- Audience laughter/applause noted in the audio report (near-definitive).\n'
            '- Exaggeration or understatement disproportionate to the situation.\n'
            '- Deadpan delivery of absurd content.'
        )
        fp_traps = 'mistaking enthusiasm, surprise, or informative statements for humor'
        fn_traps = 'dismissing deadpan jokes because the delivery is flat'
    else:
        task = 'sarcasm detection'
        yes_label = 'sarcastic'
        no_label = 'not sarcastic'
        core_def = (
            'Sarcasm is fundamentally about INCONGRUITY — a mismatch between '
            'what is literally said and what is meant, or between the content '
            'and the way it is delivered.'
        )
        signals = (
            '- Text–audio mismatch: literal praise/agreement with flat, '
            'exaggerated, or drawn-out tone.\n'
            '- Text–visual mismatch: positive words with deadpan face, eye-roll, '
            'smirk, or exaggerated gesture.\n'
            '- Content–context mismatch: over-enthusiastic statements about '
            'mundane or unpleasant things.\n'
            '- Exaggerated positive framing of something obviously negative.'
        )
        fp_traps = 'treating genuine frustration or dry humour as sarcasm'
        fn_traps = (
            'missing subtle sarcasm where the tone or face quietly contradicts '
            'the words'
        )

    synthesizer = (
        f'You are the Synthesizer in a multi-agent {task} team. You receive '
        'independent analysis reports from three modality experts (Text, '
        'Audio, Video). Produce a concise cross-modal synthesis.\n\n'
        f'{core_def}\n\nKey signals to watch for:\n{signals}\n\n'
        'Your synthesis must cover:\n'
        '1. **Modality agreement** — where do the experts agree?\n'
        '2. **Modality conflict** — where do they disagree? Disagreement '
        'between literal text and non-literal delivery is often the '
        f'STRONGEST {yes_label} signal; do not dismiss it as "experts '
        'conflicting".\n'
        '3. **Incongruity audit** — list any specific mismatches between '
        'what is said and how it is delivered.\n'
        f'4. **Tentative verdict** — on balance, {yes_label} or {no_label}? '
        'State it with a confidence level (high/medium/low). Do not make '
        'the final call here; your job is to surface evidence cleanly so '
        'the Critic and Judge can decide.'
    )
    critic = (
        f'You are the Critic in a multi-agent {task} team. You have '
        'received the modality analyses and the Synthesizer\'s integration. '
        'Your job is to audit the synthesis for BOTH directional errors — '
        'not only false positives.\n\n'
        f'{core_def}\n\nReview checklist:\n'
        '1. **Evidence grounding** — are the conclusions tied to specific '
        'observations in the modality reports, or is the synthesis hand-waving?\n'
        '2. **Under-weighted incongruity** — did the synthesis miss or '
        'down-play any text/audio or text/visual mismatch? Subtle incongruity '
        f'is the main source of missed {yes_label} cases.\n'
        f'3. **False-positive check** — is the synthesis {fp_traps}? Flag if so.\n'
        f'4. **False-negative check** — is the synthesis {fn_traps}? Flag if so.\n'
        '5. **Bias check** — MUStARD-style datasets are roughly 50/50, so a '
        f'synthesis that defaults to "{no_label}" under uncertainty is '
        'systematically wrong. If the synthesis hedges without evidence, '
        'push it to commit.\n'
        '6. **Revised verdict** — after critique, do you agree with the '
        'synthesis? Provide your own tentative call with reasoning.'
    )
    judge = (
        f'You are the Final Judge in a multi-agent {task} team. You have '
        'received three modality reports, a cross-modal synthesis, and a '
        'critic review. Make the final call.\n\n'
        f'{core_def}\n\nDecision rules:\n'
        '- When the modalities AGREE that the statement is literal and the '
        f'delivery matches the content, answer "{no_label}".\n'
        '- When any modality reports INCONGRUITY (literal words paired with '
        'incongruent delivery or context), that alone is strong evidence '
        f'for {yes_label}. Do not require all three modalities to converge.\n'
        '- Trust the Critic in BOTH directions: a flagged false-negative '
        '(missed subtle incongruity) matters as much as a flagged '
        'false-positive (genuine frustration misread as sarcasm).\n'
        '- The dataset is roughly 50/50. Do NOT default to '
        f'"{no_label}" under uncertainty — commit based on the strongest '
        'evidence available.\n'
        '- If the evidence is truly balanced, prefer the modality with the '
        'most concrete, specific grounding (a concrete observation '
        'outweighs a general impression).\n\n'
        'OUTPUT FORMAT (strict): your response MUST begin with the single '
        f'word "Yes" ({yes_label}) or "No" ({no_label}) followed by a period '
        'and one short sentence citing the most decisive piece of evidence. '
        'Do NOT prefix your answer with any reasoning or preamble before '
        'the Yes/No.'
    )
    return synthesizer, critic, judge


# =============================================================================
# MetaGPT Actions (the 6 stages of the SOP)
# =============================================================================
#
# Each Action is a metagpt.actions.Action subclass. We add Pydantic Fields for
# the configuration each stage needs, override `run()` with a signature that
# takes the data the Role feeds it, and call litellm directly instead of
# going through `self._aask`. Actions cache their last usage so the driver
# can aggregate per-sample token counts afterwards.
# =============================================================================

class _ModalityAction(Action):
    """Base class for text/audio/video analysis actions."""
    system_prompt: str = ''
    model: str = DEFAULT_MODEL
    last_usage: Dict[str, Any] = Field(default_factory=dict)


class TextAnalysisAction(_ModalityAction):
    name: str = 'TextAnalysisAction'

    async def run(self, query: str, target_sentence: str) -> str:
        messages = [
            {'role': 'system', 'content': self.system_prompt},
            {'role': 'user', 'content': (
                f'{query}\n\nDialogue transcript:\n{target_sentence}'
            )},
        ]
        loop = asyncio.get_running_loop()
        text, usage = await loop.run_in_executor(
            None, _call_llm, messages, self.model,
        )
        self.last_usage = usage
        return text or '[text analysis failed]'


class AudioAnalysisAction(_ModalityAction):
    name: str = 'AudioAnalysisAction'

    async def run(self, query: str, audio_path: Optional[str]) -> str:
        if not audio_path or not os.path.exists(audio_path):
            self.last_usage = {'prompt_tokens': 0, 'completion_tokens': 0,
                               'total_tokens': 0, 'api_calls': 0,
                               'latency': 0.0}
            return '[Audio unavailable]'

        encoded = _encode_file(audio_path)
        messages = [
            {'role': 'system', 'content': self.system_prompt},
            {'role': 'user', 'content': [
                {'type': 'text', 'text': (
                    f'{query}\n\nAnalyze the audio and produce your report.'
                )},
                {'type': 'image_url', 'image_url': {
                    'url': f'data:{_audio_mime(audio_path)};base64,{encoded}',
                }},
            ]},
        ]
        loop = asyncio.get_running_loop()
        text, usage = await loop.run_in_executor(
            None, _call_llm, messages, self.model,
        )
        self.last_usage = usage
        return text or '[audio analysis failed]'


class VideoAnalysisAction(_ModalityAction):
    name: str = 'VideoAnalysisAction'

    async def run(self, query: str, video_path: Optional[str]) -> str:
        if not video_path or not os.path.exists(video_path):
            self.last_usage = {'prompt_tokens': 0, 'completion_tokens': 0,
                               'total_tokens': 0, 'api_calls': 0,
                               'latency': 0.0}
            return '[Video unavailable]'

        encoded = _encode_file(video_path)
        messages = [
            {'role': 'system', 'content': self.system_prompt},
            {'role': 'user', 'content': [
                {'type': 'text', 'text': (
                    f'{query}\n\nAnalyze the muted video and produce your report.'
                )},
                {'type': 'image_url', 'image_url': {
                    'url': f'data:video/mp4;base64,{encoded}',
                }},
            ]},
        ]
        loop = asyncio.get_running_loop()
        text, usage = await loop.run_in_executor(
            None, _call_llm, messages, self.model,
        )
        self.last_usage = usage
        return text or '[video analysis failed]'


class SynthesisAction(Action):
    name: str = 'SynthesisAction'
    system_prompt: str = ''
    model: str = DEFAULT_MODEL
    last_usage: Dict[str, Any] = Field(default_factory=dict)

    async def run(self, query: str, text_report: str, audio_report: str,
                  video_report: str) -> str:
        messages = [
            {'role': 'system', 'content': self.system_prompt},
            {'role': 'user', 'content': (
                f'Task: {query}\n\n'
                f'=== TEXT ANALYST REPORT ===\n{text_report}\n\n'
                f'=== AUDIO ANALYST REPORT ===\n{audio_report}\n\n'
                f'=== VIDEO ANALYST REPORT ===\n{video_report}\n\n'
                'Produce your cross-modal synthesis.'
            )},
        ]
        loop = asyncio.get_running_loop()
        text, usage = await loop.run_in_executor(
            None, _call_llm, messages, self.model,
        )
        self.last_usage = usage
        return text or '[synthesis failed]'


class CriticAction(Action):
    name: str = 'CriticAction'
    system_prompt: str = ''
    model: str = DEFAULT_MODEL
    last_usage: Dict[str, Any] = Field(default_factory=dict)

    async def run(self, query: str, text_report: str, audio_report: str,
                  video_report: str, synthesis: str) -> str:
        messages = [
            {'role': 'system', 'content': self.system_prompt},
            {'role': 'user', 'content': (
                f'Task: {query}\n\n'
                f'=== TEXT ANALYST REPORT ===\n{text_report}\n\n'
                f'=== AUDIO ANALYST REPORT ===\n{audio_report}\n\n'
                f'=== VIDEO ANALYST REPORT ===\n{video_report}\n\n'
                f'=== SYNTHESIZER REPORT ===\n{synthesis}\n\n'
                'Critically review the synthesis. Identify weaknesses, '
                'overlooked evidence, and potential errors.'
            )},
        ]
        loop = asyncio.get_running_loop()
        text, usage = await loop.run_in_executor(
            None, _call_llm, messages, self.model,
        )
        self.last_usage = usage
        return text or '[critique failed]'


class JudgeAction(Action):
    name: str = 'JudgeAction'
    system_prompt: str = ''
    model: str = DEFAULT_MODEL
    last_usage: Dict[str, Any] = Field(default_factory=dict)

    async def run(self, query: str, text_report: str, audio_report: str,
                  video_report: str, synthesis: str, critique: str) -> str:
        messages = [
            {'role': 'system', 'content': self.system_prompt},
            {'role': 'user', 'content': (
                f'Task: {query}\n\n'
                f'=== TEXT ANALYST REPORT ===\n{text_report}\n\n'
                f'=== AUDIO ANALYST REPORT ===\n{audio_report}\n\n'
                f'=== VIDEO ANALYST REPORT ===\n{video_report}\n\n'
                f'=== SYNTHESIZER REPORT ===\n{synthesis}\n\n'
                f'=== CRITIC REVIEW ===\n{critique}\n\n'
                'Make your final determination. Start with "Yes" or "No".'
            )},
        ]
        loop = asyncio.get_running_loop()
        text, usage = await loop.run_in_executor(
            None, _call_llm, messages, self.model,
        )
        self.last_usage = usage
        return text or '[judgment failed]'


# =============================================================================
# MetaGPT Roles
# =============================================================================
#
# Each Role subclasses metagpt.roles.Role. It:
#   1. Uses `_watch(...)` to subscribe to upstream Actions
#   2. Uses `set_actions(...)` to install its own Action(s)
#   3. Overrides `_act()` to thread sample-specific data into its Action
#
# Sample data (target_sentence, audio_path, video_path, query) is stored as
# Pydantic fields on the Role instance. We create a fresh set of roles per
# sample (roles are stateful in MetaGPT).
# =============================================================================

class _BaseAnalyst(Role):
    """Base for modality analyst roles watching UserRequirement."""
    query: str = ''
    target_sentence: str = ''
    audio_path: Optional[str] = None
    video_path: Optional[str] = None
    model: str = DEFAULT_MODEL
    # Captures the Action's output so the driver can read it directly without
    # replaying MetaGPT's broadcast-and-observe cycle through another round.
    last_output: str = ''


class TextAnalyst(_BaseAnalyst):
    name: str = 'TextAnalyst'
    profile: str = 'Text Modality Analyst'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        system_prompt = kwargs.get('system_prompt', '')
        action = TextAnalysisAction(
            system_prompt=system_prompt, model=self.model,
        )
        self.set_actions([action])
        self._watch([UserRequirement])

    async def _act(self) -> Message:
        todo: TextAnalysisAction = self.rc.todo  # type: ignore[assignment]
        result = await todo.run(
            query=self.query, target_sentence=self.target_sentence,
        )
        self.last_output = result
        msg = Message(
            content=result, role=self.profile, cause_by=TextAnalysisAction,
            sent_from=self.name,
        )
        self.rc.memory.add(msg)
        return msg


class AudioAnalyst(_BaseAnalyst):
    name: str = 'AudioAnalyst'
    profile: str = 'Audio Modality Analyst'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        system_prompt = kwargs.get('system_prompt', '')
        action = AudioAnalysisAction(
            system_prompt=system_prompt, model=self.model,
        )
        self.set_actions([action])
        self._watch([UserRequirement])

    async def _act(self) -> Message:
        todo: AudioAnalysisAction = self.rc.todo  # type: ignore[assignment]
        result = await todo.run(query=self.query, audio_path=self.audio_path)
        self.last_output = result
        msg = Message(
            content=result, role=self.profile, cause_by=AudioAnalysisAction,
            sent_from=self.name,
        )
        self.rc.memory.add(msg)
        return msg


class VideoAnalyst(_BaseAnalyst):
    name: str = 'VideoAnalyst'
    profile: str = 'Video Modality Analyst'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        system_prompt = kwargs.get('system_prompt', '')
        action = VideoAnalysisAction(
            system_prompt=system_prompt, model=self.model,
        )
        self.set_actions([action])
        self._watch([UserRequirement])

    async def _act(self) -> Message:
        todo: VideoAnalysisAction = self.rc.todo  # type: ignore[assignment]
        result = await todo.run(query=self.query, video_path=self.video_path)
        self.last_output = result
        msg = Message(
            content=result, role=self.profile, cause_by=VideoAnalysisAction,
            sent_from=self.name,
        )
        self.rc.memory.add(msg)
        return msg


class Synthesizer(Role):
    name: str = 'Synthesizer'
    profile: str = 'Cross-Modal Synthesizer'
    query: str = ''
    model: str = DEFAULT_MODEL
    last_output: str = ''

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        system_prompt = kwargs.get('system_prompt', '')
        action = SynthesisAction(
            system_prompt=system_prompt, model=self.model,
        )
        self.set_actions([action])
        # Synthesizer becomes non-idle once any modality analysis arrives,
        # but we gate actual execution on having *all three* via _think().
        self._watch([TextAnalysisAction, AudioAnalysisAction, VideoAnalysisAction])

    async def _think(self) -> bool:
        # Wait until memory contains at least one message from each of the
        # three modality experts. MetaGPT's env.run() runs all roles in a
        # single asyncio.gather per round, which means downstream roles can
        # observe partial upstream output during the same round and react
        # early — producing duplicate downstream actions. Gating on memory
        # contents here ensures Synthesizer fires exactly once when the
        # full set of modality reports is available.
        cbs = [str(m.cause_by) for m in self.rc.memory.get()]
        has_text = any('TextAnalysisAction' in c for c in cbs)
        has_audio = any('AudioAnalysisAction' in c for c in cbs)
        has_video = any('VideoAnalysisAction' in c for c in cbs)
        if not (has_text and has_audio and has_video):
            self._set_state(-1)
            return False
        self._set_state(0)
        return True

    def _collect_reports(self) -> Dict[str, str]:
        """Pull the latest text/audio/video reports from our own memory.
        Message.cause_by is normalised to a class-path string by MetaGPT's
        `any_to_str` validator, so we match by substring."""
        reports = {'text': '[text missing]', 'audio': '[audio missing]',
                   'video': '[video missing]'}
        for msg in self.rc.memory.get():
            cb_str = str(msg.cause_by)
            if 'TextAnalysisAction' in cb_str:
                reports['text'] = msg.content
            elif 'AudioAnalysisAction' in cb_str:
                reports['audio'] = msg.content
            elif 'VideoAnalysisAction' in cb_str:
                reports['video'] = msg.content
        return reports

    async def _act(self) -> Message:
        todo: SynthesisAction = self.rc.todo  # type: ignore[assignment]
        reports = self._collect_reports()
        result = await todo.run(
            query=self.query,
            text_report=reports['text'],
            audio_report=reports['audio'],
            video_report=reports['video'],
        )
        self.last_output = result
        msg = Message(
            content=result, role=self.profile, cause_by=SynthesisAction,
            sent_from=self.name,
        )
        self.rc.memory.add(msg)
        return msg


class Critic(Role):
    name: str = 'Critic'
    profile: str = 'Critical Reviewer'
    query: str = ''
    model: str = DEFAULT_MODEL
    last_output: str = ''
    # In metagpt 0.8.2 Role._observe() already adds every popped message to
    # memory (only rc.news is filtered), so Critic's memory naturally retains
    # the upstream modality reports published in round 1 even though it
    # only *reacts* to SynthesisAction in round 3.

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        system_prompt = kwargs.get('system_prompt', '')
        action = CriticAction(system_prompt=system_prompt, model=self.model)
        self.set_actions([action])
        self._watch([SynthesisAction])

    async def _think(self) -> bool:
        cbs = [str(m.cause_by) for m in self.rc.memory.get()]
        needed = ['TextAnalysisAction', 'AudioAnalysisAction',
                  'VideoAnalysisAction', 'SynthesisAction']
        if not all(any(n in c for c in cbs) for n in needed):
            self._set_state(-1)
            return False
        self._set_state(0)
        return True

    def _collect_reports(self) -> Dict[str, str]:
        reports = {'text': '[text missing]', 'audio': '[audio missing]',
                   'video': '[video missing]', 'synthesis': '[synthesis missing]'}
        for msg in self.rc.memory.get():
            cb_str = str(msg.cause_by)
            if 'TextAnalysisAction' in cb_str:
                reports['text'] = msg.content
            elif 'AudioAnalysisAction' in cb_str:
                reports['audio'] = msg.content
            elif 'VideoAnalysisAction' in cb_str:
                reports['video'] = msg.content
            elif 'SynthesisAction' in cb_str:
                reports['synthesis'] = msg.content
        return reports

    async def _act(self) -> Message:
        todo: CriticAction = self.rc.todo  # type: ignore[assignment]
        reports = self._collect_reports()
        result = await todo.run(
            query=self.query,
            text_report=reports['text'],
            audio_report=reports['audio'],
            video_report=reports['video'],
            synthesis=reports['synthesis'],
        )
        self.last_output = result
        msg = Message(
            content=result, role=self.profile, cause_by=CriticAction,
            sent_from=self.name,
        )
        self.rc.memory.add(msg)
        return msg


class Judge(Role):
    name: str = 'Judge'
    profile: str = 'Final Judge'
    query: str = ''
    model: str = DEFAULT_MODEL
    last_output: str = ''
    # Same as Critic: metagpt 0.8.2 keeps all observed messages in memory,
    # so Judge naturally sees modality reports + synthesis + critique by the
    # time it runs in round 4.

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        system_prompt = kwargs.get('system_prompt', '')
        action = JudgeAction(system_prompt=system_prompt, model=self.model)
        self.set_actions([action])
        self._watch([CriticAction])

    async def _think(self) -> bool:
        cbs = [str(m.cause_by) for m in self.rc.memory.get()]
        needed = ['TextAnalysisAction', 'AudioAnalysisAction',
                  'VideoAnalysisAction', 'SynthesisAction', 'CriticAction']
        if not all(any(n in c for c in cbs) for n in needed):
            self._set_state(-1)
            return False
        self._set_state(0)
        return True

    def _collect_reports(self) -> Dict[str, str]:
        reports = {'text': '[text missing]', 'audio': '[audio missing]',
                   'video': '[video missing]', 'synthesis': '[synthesis missing]',
                   'critique': '[critique missing]'}
        for msg in self.rc.memory.get():
            cb_str = str(msg.cause_by)
            if 'TextAnalysisAction' in cb_str:
                reports['text'] = msg.content
            elif 'AudioAnalysisAction' in cb_str:
                reports['audio'] = msg.content
            elif 'VideoAnalysisAction' in cb_str:
                reports['video'] = msg.content
            elif 'SynthesisAction' in cb_str:
                reports['synthesis'] = msg.content
            elif 'CriticAction' in cb_str:
                reports['critique'] = msg.content
        return reports

    async def _act(self) -> Message:
        todo: JudgeAction = self.rc.todo  # type: ignore[assignment]
        reports = self._collect_reports()
        result = await todo.run(
            query=self.query,
            text_report=reports['text'],
            audio_report=reports['audio'],
            video_report=reports['video'],
            synthesis=reports['synthesis'],
            critique=reports['critique'],
        )
        self.last_output = result
        msg = Message(
            content=result, role=self.profile, cause_by=JudgeAction,
            sent_from=self.name,
        )
        self.rc.memory.add(msg)
        return msg


# =============================================================================
# Per-sample driver: build a fresh Team and run it
# =============================================================================

def _collect_usage_from_roles(roles) -> Dict[str, Any]:
    """Walk each role's Actions and sum up their `last_usage` dicts."""
    totals = {
        'total_api_calls': 0,
        'total_prompt_tokens': 0,
        'total_completion_tokens': 0,
        'total_tokens': 0,
        'stage_latencies': {},
    }
    for role in roles:
        for action in role.actions:
            u = getattr(action, 'last_usage', {}) or {}
            totals['total_api_calls'] += u.get('api_calls', 0)
            totals['total_prompt_tokens'] += u.get('prompt_tokens', 0)
            totals['total_completion_tokens'] += u.get('completion_tokens', 0)
            totals['total_tokens'] += u.get('total_tokens', 0)
            totals['stage_latencies'][action.name] = u.get('latency', 0.0)
    return totals


def _extract_final_answer_and_reports(roles) -> Dict[str, str]:
    """Each Role caches its Action output in `last_output` during `_act()`,
    so after team.run() finishes we can read them directly without relying
    on an extra 'drain' round of MetaGPT's broadcast-and-observe cycle."""
    out = {'text': '', 'audio': '', 'video': '',
           'synthesis': '', 'critique': '', 'judgment': ''}
    for r in roles:
        if isinstance(r, TextAnalyst):
            out['text'] = r.last_output
        elif isinstance(r, AudioAnalyst):
            out['audio'] = r.last_output
        elif isinstance(r, VideoAnalyst):
            out['video'] = r.last_output
        elif isinstance(r, Synthesizer):
            out['synthesis'] = r.last_output
        elif isinstance(r, Critic):
            out['critique'] = r.last_output
        elif isinstance(r, Judge):
            out['judgment'] = r.last_output
    return out


async def run_metagpt_sample_async(
    query: str, target_sentence: str,
    audio_path: Optional[str], video_path: Optional[str],
    text_system: str, audio_system: str, video_system: str,
    synthesizer_system: str, critic_system: str, judge_system: str,
    model: str, n_round: int = 4,
):
    """Build a fresh Team and run the SOP for one sample."""
    text_role = TextAnalyst(
        query=query, target_sentence=target_sentence,
        model=model, system_prompt=text_system,
    )
    audio_role = AudioAnalyst(
        query=query, audio_path=audio_path,
        model=model, system_prompt=audio_system,
    )
    video_role = VideoAnalyst(
        query=query, video_path=video_path,
        model=model, system_prompt=video_system,
    )
    synth_role = Synthesizer(
        query=query, model=model, system_prompt=synthesizer_system,
    )
    critic_role = Critic(
        query=query, model=model, system_prompt=critic_system,
    )
    judge_role = Judge(
        query=query, model=model, system_prompt=judge_system,
    )
    roles = [text_role, audio_role, video_role,
             synth_role, critic_role, judge_role]

    team = Team()
    team.hire(roles)
    team.invest(investment=10.0)  # high enough to avoid cost-abort
    team.run_project(query)
    await team.run(n_round=n_round)

    reports = _extract_final_answer_and_reports(roles)
    usage = _collect_usage_from_roles(roles)
    return reports, usage


def _parse_yes_no(text: str) -> str:
    """Extract 'Yes'/'No' from the judge's reply."""
    if not text:
        return ''
    head = text.strip()[:16].lower()
    if head.startswith('yes'):
        return 'Yes'
    if head.startswith('no'):
        return 'No'
    lower = text.lower()
    if 'yes' in lower and 'no' not in lower[:lower.find('yes')+3]:
        return 'Yes'
    if 'no' in lower:
        return 'No'
    return ''


# =============================================================================
# Instance runner (sync wrapper; one fresh event loop per thread)
# =============================================================================

def run_instance(test_file, dataset, dataset_name, output_file,
                 ctm_prompts, pipeline_prompts, model):
    try:
        config = get_dataset_config(dataset_name)
        sample = dataset[test_file]
        target_sentence = config.get_text_field(sample)
        label = config.get_label_field(sample)
        query = config.get_task_query()

        audio_path = get_audio_path(test_file, dataset_name)
        video_path = get_muted_video_path(test_file, dataset_name)
        if not os.path.exists(audio_path):
            audio_path = None
        if not os.path.exists(video_path):
            video_path = None

        synth_prompt, critic_prompt, judge_prompt = pipeline_prompts
        start_time = time.time()
        reports, usage_stats = asyncio.run(run_metagpt_sample_async(
            query=query, target_sentence=target_sentence,
            audio_path=audio_path, video_path=video_path,
            text_system=ctm_prompts['language_processor']['system_prompt'],
            audio_system=ctm_prompts['audio_processor']['system_prompt'],
            video_system=ctm_prompts['video_processor']['system_prompt'],
            synthesizer_system=synth_prompt,
            critic_system=critic_prompt,
            judge_system=judge_prompt,
            model=model,
        ))
        elapsed = time.time() - start_time

        final_answer = reports.get('judgment', '') or ''
        parsed = _parse_yes_no(final_answer)
        print(
            f'[{test_file}] {elapsed:.1f}s | api={usage_stats["total_api_calls"]} '
            f'tok={usage_stats["total_tokens"]} | {final_answer[:60]}'
        )

        result = {
            test_file: {
                'answer': [final_answer],
                'parsed_answer': [parsed],
                'label': label,
                'method': 'metagpt_framework',
                'latency': elapsed,
                'api_calls': usage_stats['total_api_calls'],
                'prompt_tokens': usage_stats['total_prompt_tokens'],
                'completion_tokens': usage_stats['total_completion_tokens'],
                'total_tokens': usage_stats['total_tokens'],
                'stage_latencies': usage_stats['stage_latencies'],
                'stage_outputs': {
                    'text_report': reports.get('text', ''),
                    'audio_report': reports.get('audio', ''),
                    'video_report': reports.get('video', ''),
                    'synthesis': reports.get('synthesis', ''),
                    'critique': reports.get('critique', ''),
                },
            }
        }

        with file_lock:
            with open(output_file, 'a', encoding='utf-8') as f:
                f.write(json.dumps(result, ensure_ascii=False) + '\n')
        return f'OK {test_file}'

    except Exception as e:
        print(f'[{test_file}] ERROR: {e}')
        import traceback
        traceback.print_exc()
        return f'FAIL {test_file}: {e}'


# =============================================================================
# Parallel runner
# =============================================================================

def load_processed_keys(output_file):
    processed = set()
    try:
        with open(output_file, 'r', encoding='utf-8') as f:
            for line in f:
                if line.strip():
                    processed.update(json.loads(line).keys())
    except FileNotFoundError:
        pass
    return processed


def run_parallel(dataset, dataset_name, max_workers, output_file, resume,
                 sleep_between, ctm_prompts, pipeline_prompts, model):
    test_list = list(dataset.keys())

    if resume:
        processed = load_processed_keys(output_file)
        test_list = [k for k in test_list if k not in processed]
        print(f'Resume: {len(processed)} done, {len(test_list)} remaining')
    else:
        with open(output_file, 'w', encoding='utf-8'):
            pass

    if not test_list:
        print('Nothing to do.')
        return

    print('=' * 60)
    print(f'MetaGPT framework SOP (6 roles) | Model: {model}')
    print(f'Samples: {len(test_list)} | Workers: {max_workers}')
    print(f'Output: {output_file}')
    print('=' * 60)

    start_time = time.time()
    completed = 0

    if max_workers == 1 and sleep_between > 0:
        for t in test_list:
            run_instance(t, dataset, dataset_name, output_file,
                         ctm_prompts, pipeline_prompts, model)
            completed += 1
            print(f'Progress: {completed}/{len(test_list)}')
            if completed < len(test_list):
                time.sleep(sleep_between)
    else:
        with ThreadPoolExecutor(max_workers=max_workers) as executor:
            futures = {
                executor.submit(
                    run_instance, t, dataset, dataset_name, output_file,
                    ctm_prompts, pipeline_prompts, model,
                ): t for t in test_list
            }
            for future in as_completed(futures):
                completed += 1
                try:
                    result = future.result()
                    print(f'Progress: {completed}/{len(test_list)} - {result}')
                except Exception as exc:
                    print(f'Error: {exc}')

    wall_time = time.time() - start_time
    _print_summary(output_file, wall_time)


def _print_summary(output_file, wall_time):
    total_api = total_pt = total_ct = total_tok = 0
    latencies: List[float] = []
    n = 0
    try:
        with open(output_file) as f:
            for line in f:
                if not line.strip():
                    continue
                for _, val in json.loads(line).items():
                    n += 1
                    total_api += val.get('api_calls', 0)
                    total_pt += val.get('prompt_tokens', 0)
                    total_ct += val.get('completion_tokens', 0)
                    total_tok += val.get('total_tokens', 0)
                    latencies.append(val.get('latency', 0.0))
    except Exception as e:
        print(f'Warning: {e}')
        return

    if n == 0:
        return

    cost = total_pt / 1e6 * 0.075 + total_ct / 1e6 * 0.30
    print(f'\n{"=" * 60}')
    print('METAGPT (framework) PERFORMANCE & COST SUMMARY')
    print('=' * 60)
    print(f'Samples:                  {n}')
    print(f'Wall-clock:               {wall_time:.1f}s')
    print('-' * 40)
    print(f'Total API Calls:          {total_api}')
    print(f'Avg API Calls/Sample:     {total_api / n:.1f}')
    print(f'Avg Latency/Sample:       {sum(latencies) / n:.2f}s')
    print('-' * 40)
    print(f'Total Prompt Tokens:      {total_pt:,}')
    print(f'Total Completion Tokens:  {total_ct:,}')
    print(f'Total Tokens:             {total_tok:,}')
    print(f'Avg Tokens/Sample:        {total_tok / n:,.0f}')
    print('-' * 40)
    print(f'Estimated Cost:           ${cost:.4f}')
    print(f'Avg Cost/Sample:          ${cost / n:.6f}')
    print('=' * 60 + '\n')


# =============================================================================
# CLI
# =============================================================================

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='MetaGPT framework baseline for affective detection. '
                    'Uses metagpt.Role/Action/Team directly — run in the '
                    'dedicated ctm-baselines conda env.',
    )
    parser.add_argument('--dataset_name', type=str, default='mustard',
                        choices=['urfunny', 'mustard'])
    parser.add_argument('--dataset', type=str, default=None)
    parser.add_argument('--output', type=str, default=None)
    parser.add_argument('--model', type=str, default=DEFAULT_MODEL)
    parser.add_argument('--max_workers', type=int, default=4)
    parser.add_argument('--resume', action='store_true')
    parser.add_argument('--sleep', type=float, default=0)
    args = parser.parse_args()

    config = get_dataset_config(args.dataset_name)
    if args.dataset is None:
        args.dataset = config.get_default_dataset_path()

    ctm_prompts = _load_ctm_prompts(args.dataset_name)
    pipeline_prompts = _build_pipeline_prompts(args.dataset_name)

    output_file = args.output or f'metagpt_{args.dataset_name}.jsonl'

    dataset = load_data(args.dataset)
    print(f'Dataset: {args.dataset_name} | Model: {args.model} | '
          f'Samples: {len(dataset)}')

    run_parallel(
        dataset, args.dataset_name,
        max_workers=args.max_workers, output_file=output_file,
        resume=args.resume, sleep_between=args.sleep,
        ctm_prompts=ctm_prompts, pipeline_prompts=pipeline_prompts,
        model=args.model,
    )
