from typing import Any

class TfidfVectorizer:
    def __init__(self, **kwargs: Any) -> None: ...
    def fit_transform(self, raw_documents: Any, y: Any = None) -> Any: ...
    def transform(self, raw_documents: Any) -> Any: ...
